"""Add status column to Project

Revision ID: 8d12f0dbe401
Revises: 3545f87f7a7f
Create Date: 2025-05-08 21:10:14.732688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d12f0dbe401'
down_revision = '3545f87f7a7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
