"""Adding Icon on Submodule

Revision ID: 96a418eeb147
Revises: 608307202db6
Create Date: 2025-05-09 23:02:01.278635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a418eeb147'
down_revision = '608307202db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submodule', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
