"""Updated User model: removed active, added is_active and activation_token

Revision ID: b86ac50773bc
Revises: 7cffec930b80
Create Date: 2025-03-20 20:41:46.434623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b86ac50773bc'
down_revision = '7cffec930b80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('activation_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(None, ['activation_token'])
        batch_op.drop_column('active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activation_token')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
