"""Add Module table and module_roles association

Revision ID: ea1100ec8b77
Revises: 7bc70f9c0606
Create Date: 2025-05-08 13:40:30.833593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1100ec8b77'
down_revision = '7bc70f9c0606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sequence', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module', schema=None) as batch_op:
        batch_op.drop_column('sequence')

    # ### end Alembic commands ###
